<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Expired_doctitle_2975</name>
   <tag></tag>
   <elementGuidId>d662086d-a216-4771-970c-1ca931968b54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doctitle_2975</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doctitle_2975']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#doctitle_2975</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bd5a616-f7cb-49af-87c9-b7ca5703e1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctitle_2975</value>
      <webElementGuid>64d0e9cf-3ed3-419a-8f81-2a71974f42f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/12/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123</value>
      <webElementGuid>abc7de7c-af62-4bce-b323-9acf5e81b8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentProperties(2975, 1036, 1199)</value>
      <webElementGuid>2c41a634-eed3-46ee-b9c2-aaa819db082a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>63fd5017-e0a5-44ae-bcde-e84c669d447a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctitle custom-link-color</value>
      <webElementGuid>39fe20e1-df16-4784-b4c5-8a7266386108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>7f030205-a1c0-4876-8e22-7317ac8bd464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctitle_2975&quot;)</value>
      <webElementGuid>73fc9edb-ff65-451d-b01c-e04e4a7ccc04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doctitle_2975']</value>
      <webElementGuid>ff3be0ea-5097-4a87-8fab-4106775480f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-row-2975']/div[2]/a</value>
      <webElementGuid>62392bd5-e7bc-445f-bc58-d08b0ff7a9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'test')])[3]</value>
      <webElementGuid>9f28b738-4dbb-4022-b933-af67539d159d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expired'])[2]/following::a[1]</value>
      <webElementGuid>ecd25e62-a55c-4bd4-8a0b-7ccc028dacb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[3]/following::a[1]</value>
      <webElementGuid>f776e33e-aa8d-4486-be44-d8470969f1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similatan, Syndy'])[10]/preceding::a[1]</value>
      <webElementGuid>ddd97b58-a56e-451f-aae8-ce1d7152e325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[38]</value>
      <webElementGuid>d8f7c0c6-af7a-43bb-a3a6-0587f3893975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[2]/a</value>
      <webElementGuid>27cb25b4-bfd5-439c-b299-73d0124147fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doctitle_2975' and @title = 'DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/12/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123' and @href = '#' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>89fdf38a-3a94-473f-834e-313828286dd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
