<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preview_custom-link-color</name>
   <tag></tag>
   <elementGuidId>d14e7966-9bd9-4490-b39e-19c585152ef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-10 > a.custom-link-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='DisplayDocumentCheckInRevisionModal(2975)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Check In Revision&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0792eafb-f35a-4a31-96cb-9a365374a274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1b4fc56f-37f9-4f86-ba67-2ccb61ef10b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-link-color</value>
      <webElementGuid>6ed2f030-6467-49be-a64a-ae3b97e4d0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentCheckInRevisionModal(2975)</value>
      <webElementGuid>547c20fe-82ad-4928-828f-30c7caf7e093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check In Revision</value>
      <webElementGuid>37e24e0f-595a-455b-accf-7ac9f0b44929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-document-properties-container&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@id=&quot;dapreview_21128&quot;]/div[@class=&quot;col-sm-10&quot;]/a[@class=&quot;custom-link-color&quot;]</value>
      <webElementGuid>2c69f99b-f000-498a-bdf6-83bf02d74679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='DisplayDocumentCheckInRevisionModal(2975)']</value>
      <webElementGuid>d86eb575-dccf-4852-87d5-8e3bdf80a00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dapreview_21128']/div[2]/a)[2]</value>
      <webElementGuid>cec53795-566b-4464-89ca-2f5816c28e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Check In Revision')]</value>
      <webElementGuid>13006be6-c4bc-4877-96f3-b2ca054bb5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/following::a[1]</value>
      <webElementGuid>1267c9ae-c639-4169-aae7-1fd8a3c3f2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIONS'])[1]/following::a[2]</value>
      <webElementGuid>51651712-b8fd-4062-951b-a198a700b828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Favorites'])[1]/preceding::a[12]</value>
      <webElementGuid>dc31281c-8e6e-4801-af5b-108876ea90bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check In Revision']/parent::*</value>
      <webElementGuid>26f64da0-ea9a-44fd-a196-c07b03493fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[45]</value>
      <webElementGuid>9dd46014-dcd6-442e-9b95-dd3d7d7a4735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div[2]/a</value>
      <webElementGuid>1490cfae-0a58-472b-bee5-0cb6a24e6598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Check In Revision' or . = 'Check In Revision')]</value>
      <webElementGuid>00e75926-f118-42b1-87e6-a1ff486154ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
