<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiry Date_ValidTo</name>
   <tag></tag>
   <elementGuidId>ece6231e-ee56-455b-93c8-d114e29865e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValidTo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValidTo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ValidTo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed64adb2-cb18-452a-b98f-bc3e0ac8c9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>27fa0224-9466-4667-8481-3e466d95be16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValidTo</value>
      <webElementGuid>c2cb7fe7-f73d-4ea1-8cf2-846a3aac7cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValidTo</value>
      <webElementGuid>a5e6caa2-b6e9-4c1d-a130-6d8c8c8e1cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ec371e11-e838-42bf-b011-b6cb2b1c198b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2025-11-05</value>
      <webElementGuid>dec70664-d0f6-4eca-af3c-2ebd66f33309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValidTo&quot;)</value>
      <webElementGuid>e747e349-9df2-4256-8dd7-c5664bb79c72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValidTo']</value>
      <webElementGuid>d0ef460d-98d0-4e64-bfdf-394273d9d6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkinRevisionModal']/div/div/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>eb6ab1dd-9124-41db-ba8a-bb65fba2675f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>1ab469b4-883f-4f76-9559-04a8bb75501b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ValidTo' and @name = 'ValidTo' and @type = 'date']</value>
      <webElementGuid>b9ff212c-8c7f-4630-8775-cc186ee5525f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
