<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Document Date_ValidFrom</name>
   <tag></tag>
   <elementGuidId>c1dacf10-04ff-43fd-bbc9-429e05b747ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValidFrom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValidFrom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ValidFrom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58ea8f8e-7c01-49b2-abe6-aabaca19fb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc2d08db-be49-4ada-ab61-564c6588ba31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValidFrom</value>
      <webElementGuid>ec82d40e-f841-4a21-a1a6-f2bb456d33f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValidFrom</value>
      <webElementGuid>a6edeccd-1d16-4246-8eee-996b30259e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d15ea6ce-f053-4194-8ea7-c86f0efe16e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2025-11-04</value>
      <webElementGuid>6874f0f1-fac9-4a90-be8b-f0a412036a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValidFrom&quot;)</value>
      <webElementGuid>6bd22554-f9bb-4ae5-b73b-658f20bcb0ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValidFrom']</value>
      <webElementGuid>3c79f0b1-90f3-4106-9c2b-ec7cf5d2b5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkinRevisionModal']/div/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>01d3f482-df58-412b-9e3d-0c7785f9a3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>0c9c73dc-2e72-4994-9ea0-4b2a51d1d645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ValidFrom' and @name = 'ValidFrom' and @type = 'date']</value>
      <webElementGuid>09434ca7-de3c-40ca-80ee-6b1a8545dc22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
