<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse File_Filename</name>
   <tag></tag>
   <elementGuidId>90ef2296-9668-44ed-9d70-2d0196034f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Filename</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Filename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Filename</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f39045e-ed56-4d32-bc64-24a19db70af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>98dd2e62-36fa-4342-b84a-46d40846c098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Filename</value>
      <webElementGuid>72b39431-0238-46eb-a5cd-bfc8e4204600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Filename</value>
      <webElementGuid>b5a350dd-f1d7-4b33-9324-656445ea704d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>5d7a82b3-4f62-47dc-b353-133bf3905c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fbacfdc5-3c75-4750-b1c9-818b808dad29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Filename&quot;)</value>
      <webElementGuid>7aee15bd-5851-4842-97e0-03da2307bb57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Filename']</value>
      <webElementGuid>0e3787f0-a9be-4eb5-a21b-da7c0e73e17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkinRevisionModal']/div/div/div[2]/div/div/div[2]/div/div/input[3]</value>
      <webElementGuid>96474055-d8a0-4179-8d56-5166b38541f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>4a70c033-cc2f-4803-8e39-39f67c0bd9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Filename' and @name = 'Filename' and @type = 'text']</value>
      <webElementGuid>512a18be-92c8-4906-8b7d-2eb5c57a6a0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
