<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse File_inputid</name>
   <tag></tag>
   <elementGuidId>8c561832-22e8-408b-9103-52987bc3f0f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#inputid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbc1e1f4-a658-4d71-90c3-6f51f7d12369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3e5d1e4e-113c-4108-b975-005bb84435b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputid</value>
      <webElementGuid>e040a275-2767-4d52-90d7-7648b3535ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Filename</value>
      <webElementGuid>1592f0ad-8c57-4d14-8488-d9d01bb80d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>0b9b0da4-2726-4111-9bb6-650a7bccb811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputid&quot;)</value>
      <webElementGuid>b4627f3a-6c2c-44b9-8c0c-66ca56dfdf43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputid']</value>
      <webElementGuid>5a303256-3c2c-47f2-a42b-10a7bd6a2034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkinRevisionModal']/div/div/div[2]/div/div/div[2]/div/div/input[2]</value>
      <webElementGuid>a714f0eb-1568-46ba-bad5-c43b679ef132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input[2]</value>
      <webElementGuid>a237e409-f26f-4a51-93c8-be327920b5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputid' and @name = 'Filename' and @type = 'file']</value>
      <webElementGuid>758c5e3d-262e-4622-9f68-5986d54d30f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
