<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Content_doc-metadata-tab</name>
   <tag></tag>
   <elementGuidId>d25bb48d-00b7-470e-aa5e-6adb2bfbdf22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doc-metadata-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doc-metadata-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Meta Tag&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e34d3b4b-4e70-46c2-a2ab-1b2a0f967e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>90ecb346-ef3f-4f2a-99a4-659b43416019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doc-metadata-tab</value>
      <webElementGuid>31c21fbf-8c3b-47fc-84d8-64cbc1804a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>cc2742ad-6cb6-4333-9776-7a66cb1a172e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#doc-metadata</value>
      <webElementGuid>f54d8b32-4326-462f-9168-93ceac77c28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b28de76b-315d-4fd5-bba7-715c5590aa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>metadata</value>
      <webElementGuid>04d049ec-d96d-4c93-90ba-48d8afd297d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9d6bc44-cd5e-48bc-949a-1235f1567209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Meta Tag</value>
      <webElementGuid>7adcd8c5-e860-4c5e-b3a1-b82a65e60fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doc-metadata-tab&quot;)</value>
      <webElementGuid>33296f60-d547-4a03-8088-d8ae43f4e2ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doc-metadata-tab']</value>
      <webElementGuid>41dd3047-890c-44e2-9c3a-25c6e872acaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tabDocumentDetails']/li[6]/a</value>
      <webElementGuid>7db5ed4f-4b1c-43a8-93dc-bbcc4066a90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Meta Tag')]</value>
      <webElementGuid>e7db498f-700b-4fef-a73d-0ea596109f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content'])[2]/following::a[1]</value>
      <webElementGuid>3c2a7606-383c-407a-9d83-e36d2bcf73a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[2]/following::a[2]</value>
      <webElementGuid>eae2448e-56b4-4df5-80b4-38e1237adf47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Log'])[1]/preceding::a[1]</value>
      <webElementGuid>cf563d8e-564e-4110-80b9-e2919d671efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[5]/preceding::a[2]</value>
      <webElementGuid>dba24246-4302-496a-88ab-4612446e4fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#doc-metadata')]</value>
      <webElementGuid>81d8034f-2840-49e7-bdfc-805008f1885e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[6]/a</value>
      <webElementGuid>498770b8-938b-48f9-a025-f3838e9d125f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doc-metadata-tab' and @href = '#doc-metadata' and (text() = 'Meta Tag' or . = 'Meta Tag')]</value>
      <webElementGuid>b2570299-c2ba-4399-9d48-5816663739bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
