<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Meta Tag_doc-access-log-tab</name>
   <tag></tag>
   <elementGuidId>56f9ddbe-4937-42de-a570-c7a9612dd2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doc-access-log-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doc-access-log-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Access Log&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73083547-7c77-40c5-852e-8fb7d6ee64d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>51a2d6a1-a75c-4570-9dd5-49e7e2baba74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doc-access-log-tab</value>
      <webElementGuid>3f93d65f-9d51-4abf-ae5d-e3fcc5ab12d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e6c6cce8-0f7f-438b-9b6e-db8899bf5dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#doc-acccess-log</value>
      <webElementGuid>52061568-bf79-4771-beb9-60edc2fa6ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>9aaed6be-29da-4276-a6d2-9f2f3ab0d31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>accesslog</value>
      <webElementGuid>876ed4ac-3896-46a6-b828-8073b6999797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e7fa7e75-f795-4645-84a3-50c019c843de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Access Log</value>
      <webElementGuid>67880402-f99e-43ee-9a48-7e1ce7cb0a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doc-access-log-tab&quot;)</value>
      <webElementGuid>85219164-0ab7-4eda-bdac-ed25812eb151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doc-access-log-tab']</value>
      <webElementGuid>72860018-e90b-4b78-8764-689e543476ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tabDocumentDetails']/li[7]/a</value>
      <webElementGuid>4092919e-af05-4c99-abb4-9e0065652a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Access Log')]</value>
      <webElementGuid>fc7b1acd-a702-4c81-bd05-69dc1036cec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meta Tag'])[2]/following::a[1]</value>
      <webElementGuid>50d259ca-5aa1-488e-9a6b-4edb0dfbe7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content'])[2]/following::a[2]</value>
      <webElementGuid>f2869937-86cd-4197-9161-4fa345e2356d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[5]/preceding::a[1]</value>
      <webElementGuid>c9c1fb0b-9e39-4fe7-ad50-4b11e1c9a100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Access Log']/parent::*</value>
      <webElementGuid>f74bf3a3-96df-47d8-a10b-847d5ba0eef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#doc-acccess-log')]</value>
      <webElementGuid>577ca52f-6118-45ae-9315-c02f32bd8452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[7]/a</value>
      <webElementGuid>dc142d8c-3a80-43e1-b876-654d8228bc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doc-access-log-tab' and @href = '#doc-acccess-log' and (text() = 'Access Log' or . = 'Access Log')]</value>
      <webElementGuid>9c2a65f7-00b8-440b-8585-9a9f7b32bd9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
