<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Revisions_doc-notes-tab</name>
   <tag></tag>
   <elementGuidId>53adb944-b59d-43b1-a195-bcf2d3f002e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doc-notes-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doc-notes-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Notes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>474e23f0-c79a-498d-a957-b8aaa7a98ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>2eb56fee-d36b-4ee8-9d46-a16fa7e5e5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doc-notes-tab</value>
      <webElementGuid>699ebb5f-9f5d-4183-99f1-bfe2ea8796dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ca8e55da-d29b-4d4b-93f9-fd0eee26bf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#doc-notes</value>
      <webElementGuid>0cac1653-1cbd-4b5f-9e4b-6b770a2ec8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a7a2c4ca-2363-4bf5-a8f7-604819ef1fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>notes</value>
      <webElementGuid>7a6bd0a1-494c-4d15-8adc-eb1d5d61b186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0ca057c5-af9a-4deb-955f-d022fab22ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>6505e641-bd80-4e51-a223-e047ea6cf315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doc-notes-tab&quot;)</value>
      <webElementGuid>a5cb2404-a2a1-4c3d-8cd0-96efd8237b35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doc-notes-tab']</value>
      <webElementGuid>a3b657a8-0ab2-4c14-9206-8eed3912165f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tabDocumentDetails']/li[4]/a</value>
      <webElementGuid>43655b4b-b10c-45d5-b0fc-e54e08150797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Notes')]</value>
      <webElementGuid>f1271b18-b9f1-405d-acb0-cf368b0734b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revisions'])[1]/following::a[1]</value>
      <webElementGuid>2f39c8a8-69d8-42d9-897f-8d82c51cb9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indices'])[1]/following::a[2]</value>
      <webElementGuid>cf2ee2c4-196e-4dd2-8d54-db3cc0316e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content'])[2]/preceding::a[1]</value>
      <webElementGuid>a66e9be0-4596-44db-a7c7-2834fd769338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meta Tag'])[2]/preceding::a[2]</value>
      <webElementGuid>5faf69bb-77b5-4940-9e58-e25a295c3628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#doc-notes')]</value>
      <webElementGuid>d5f9d63b-16c1-4f24-ae04-6af4b8cc8e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[4]/a</value>
      <webElementGuid>76f4aedc-189e-487c-bdcd-0b5063b82eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doc-notes-tab' and @href = '#doc-notes' and (text() = 'Notes' or . = 'Notes')]</value>
      <webElementGuid>4cb5ae2f-fe49-4469-a561-a4899112692d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
