<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AssignRemove Users_txtSearchUser</name>
   <tag></tag>
   <elementGuidId>e5ca37a9-5be3-4e5b-8ce7-ad6707e72182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSearchUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSearchUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search Users&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29a3492c-d253-47e0-893c-5dd6968a77c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSearchUser</value>
      <webElementGuid>9a603bb1-f948-4224-8eab-09dbb36bddf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table_searchUsers</value>
      <webElementGuid>65913026-9c45-4868-8dad-b6c8b45fad1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>42682c23-5a9e-4920-8bb3-481c53116a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>429b176d-2011-4d09-bda6-e68c8d7768b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Users</value>
      <webElementGuid>055a9e4d-f116-4306-8b80-36031bb1d7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSearchUser&quot;)</value>
      <webElementGuid>4b2b5fd0-e337-4d78-9771-c45cb96de646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSearchUser']</value>
      <webElementGuid>9dadb837-93f8-46ef-beff-20466dc00569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-assign-templateUser']/div/div/div[2]/div/input</value>
      <webElementGuid>c8e1e4ca-b913-45ce-accc-a3f20a337357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7cf8f2f2-5c97-481d-8ea9-72283b3957e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtSearchUser' and @name = 'table_searchUsers' and @type = 'text' and @placeholder = 'Search Users']</value>
      <webElementGuid>77f90e5f-0591-426b-809d-a10d3cf447b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
