<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Manato, James Mark_SelectedMembers</name>
   <tag></tag>
   <elementGuidId>ae8a47b3-2634-45b9-9d2a-53505b3ad082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='SelectedMembers'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Manato, James Mark&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bc693cc-533f-4888-8f58-9858b4aa43f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c4b1e8e1-0f9c-4576-8012-880824524071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectedMembers</value>
      <webElementGuid>02ac288f-0c63-4d7d-a045-f30ab31bb816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>310</value>
      <webElementGuid>8e865c8a-8cd5-4a47-b906-583da483303c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containet-list-user&quot;)/div[@class=&quot;form-horizontal mt-0&quot;]/div[@class=&quot;table table-responsive&quot;]/table[@class=&quot;table table-sm table-striped table-hover table-head-fixed text-nowrap&quot;]/tbody[1]/tr[@class=&quot;clickable-row&quot;]/td[1]/div[@class=&quot;checkbox&quot;]/input[1]</value>
      <webElementGuid>503e3fbf-62a5-4a32-96eb-1386106ed28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='SelectedMembers'])[3]</value>
      <webElementGuid>9eeaf7aa-3ca6-4150-adfb-5ac94a05c8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containet-list-user']/div/div/table/tbody/tr[3]/td/div/input</value>
      <webElementGuid>8147b20d-13b4-49dd-adbd-2cbdf71c64e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/input</value>
      <webElementGuid>2581bbb9-2e33-432d-8458-82805840aac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'SelectedMembers']</value>
      <webElementGuid>8b4cead7-fddf-49f5-8af6-1957b117226d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
