<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bojo, Randell James_SelectedMembers</name>
   <tag></tag>
   <elementGuidId>c06f13be-4ea1-4075-9dbe-31d2baedbe2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SelectedMembers&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SelectedMembers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;SelectedMembers&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a740972a-7820-47b7-bbbb-373e6f81373d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9aa2b172-0fdc-42f8-9426-df64d0c45b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectedMembers</value>
      <webElementGuid>ae4f965c-e7f0-44b6-8ef3-3d131c0d21d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>309</value>
      <webElementGuid>b8e9ba97-d6f3-4045-9c8a-d4937628f762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;containet-list-user&quot;)/div[@class=&quot;form-horizontal mt-0&quot;]/div[@class=&quot;table table-responsive&quot;]/table[@class=&quot;table table-sm table-striped table-hover table-head-fixed text-nowrap&quot;]/tbody[1]/tr[@class=&quot;clickable-row&quot;]/td[1]/div[@class=&quot;checkbox&quot;]/input[1]</value>
      <webElementGuid>2934b193-ce9a-4925-b477-8303032b8177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SelectedMembers']</value>
      <webElementGuid>9d478e4b-e43c-4629-b5de-96a9bd10abb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containet-list-user']/div/div/table/tbody/tr/td/div/input</value>
      <webElementGuid>2c53cf95-2311-42d7-b75c-83ac7cc28c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>a3319166-c815-4a1a-ac17-684bf04c1551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'SelectedMembers']</value>
      <webElementGuid>2dcd59c2-c0db-40af-b728-1aa5999298b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
