<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manalo, Nicole_doctitle_2977</name>
   <tag></tag>
   <elementGuidId>8d1b300c-b313-4d1b-a9c5-77fc1606a351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doctitle_2977']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#doctitle_2977</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#doctitle_2977</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e28b87b-9d85-4ea0-b5c0-6d741fa83c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctitle_2977</value>
      <webElementGuid>3388c080-5a91-4545-9187-89fa048c7aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/12/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123</value>
      <webElementGuid>963c359e-4372-47a2-92ae-daa892a8e8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentProperties(2977, 1036, 1199)</value>
      <webElementGuid>f6b6b4e8-7395-4a4c-93fc-e3c7c1075b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>02be3562-4f82-40fd-9cf4-b31f0e762e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctitle custom-link-color</value>
      <webElementGuid>d5c1102f-9b9d-4a1e-8b12-0e98e4fe039e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>c69f0bd9-b732-4e0a-b067-d47923d7afc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctitle_2977&quot;)</value>
      <webElementGuid>ca87d449-2894-4be9-9ff1-37991582a9be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doctitle_2977']</value>
      <webElementGuid>07dd7d3f-0754-4125-8bf2-2d2395e056a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-row-2977']/div[2]/a</value>
      <webElementGuid>92f1d287-0022-49d7-bfe6-207221ff9835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'test')]</value>
      <webElementGuid>2c119b41-4a27-412b-b236-9763060f783e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manalo, Nicole'])[2]/following::a[1]</value>
      <webElementGuid>fec1dfb0-e113-4ea5-9081-c23440367ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similatan, Syndy'])[8]/preceding::a[1]</value>
      <webElementGuid>32bcb15f-b275-4e6c-872f-6ca410e57af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>19da7083-3703-48dc-979e-8b8f25aab3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[36]</value>
      <webElementGuid>a202f0e7-e957-4364-84f3-1c9029fcbe03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/a</value>
      <webElementGuid>4eb2bc5c-fb64-4877-a3fa-69a1a5199c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doctitle_2977' and @title = 'DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/12/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123' and @href = '#' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>16073888-d7a0-41b4-8da4-6acbe5a26e05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
