<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manalo, Nicole_doctitle_2968</name>
   <tag></tag>
   <elementGuidId>ce1fa783-beff-44aa-a89c-93ec7908b380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doctitle_2968</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doctitle_2968']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;system_prompt_cases&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>980b8aac-d15c-44eb-af58-c4cd95571863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctitle_2968</value>
      <webElementGuid>15d211ec-b9a8-4c07-91cd-2566398be581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:system_prompt_cases test case for check in document DocumentDate:11/05/2025 CheckedInDate:11/05/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123</value>
      <webElementGuid>b7f97828-be87-43d8-844e-b5d54df8b369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentProperties(2968, 1036, 1199)</value>
      <webElementGuid>f48609fe-a531-4532-9583-0683c50757b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e7a65b53-68f6-42b9-81dd-d89a6a58149e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctitle custom-link-color</value>
      <webElementGuid>ad8c5fb7-77db-4f41-8678-71a39e46d9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>system_prompt_cases</value>
      <webElementGuid>063871cc-17e1-4824-bd84-5c519789a1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctitle_2968&quot;)</value>
      <webElementGuid>8ed240da-ad43-47b9-98dd-b9c8cf4fda1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doctitle_2968']</value>
      <webElementGuid>643dbf9c-b5d9-4f66-a191-4be924ef8b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-row-2968']/div[2]/a</value>
      <webElementGuid>1a58018f-6b19-42b8-a308-c557c15ae2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'system_prompt_cases')]</value>
      <webElementGuid>2f6fd080-64b6-44ad-be6c-da3eb7963012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manalo, Nicole'])[2]/following::a[1]</value>
      <webElementGuid>8603543f-33e7-4123-9389-8c98c9ca672e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similatan, Syndy'])[12]/preceding::a[1]</value>
      <webElementGuid>347222a5-78e6-4e91-a7f1-d231fa3c2a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='system_prompt_cases']/parent::*</value>
      <webElementGuid>b2f08fab-3b61-4fe2-8108-5dcb3d165ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[40]</value>
      <webElementGuid>4c8e6557-a5aa-48ab-ab13-248779da1e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div[2]/a</value>
      <webElementGuid>4bb2817f-e0f3-48c0-a698-2187774c0164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doctitle_2968' and @title = 'DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:system_prompt_cases test case for check in document DocumentDate:11/05/2025 CheckedInDate:11/05/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123' and @href = '#' and (text() = 'system_prompt_cases' or . = 'system_prompt_cases')]</value>
      <webElementGuid>ba76e43a-a1e7-49fb-8de8-e568126539b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
