<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preview_custom-link-color</name>
   <tag></tag>
   <elementGuidId>74e42a46-b771-49b4-a863-6f5b7285507f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='LoadCheckOutPartialViewSingleFile(2977)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Folder View&quot;i >> internal:role=link[name=&quot;Check Out&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e44e540f-8b66-478c-937a-e81f36a395c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cfdea532-37aa-4543-8287-521c774d7298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-link-color</value>
      <webElementGuid>3383bcc8-6858-4fad-b3c3-8f9546c0bb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>LoadCheckOutPartialViewSingleFile(2977)</value>
      <webElementGuid>612f097b-fef7-4096-8e2a-b9970fbcced2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check Out</value>
      <webElementGuid>a58ed022-292f-4a8e-88ed-43d1df4a37ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-document-properties-container&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@id=&quot;dadownload_21128&quot;]/div[@class=&quot;col-sm-8&quot;]/a[@class=&quot;custom-link-color&quot;]</value>
      <webElementGuid>bfcde154-ebcc-4baf-b396-ef00fa51b1a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='LoadCheckOutPartialViewSingleFile(2977)']</value>
      <webElementGuid>4ea7ae1b-ebe2-44f5-970f-85d0d730ceec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dadownload_21128']/div[2]/a)[2]</value>
      <webElementGuid>2c0a23d7-23f6-45c3-b0ec-bbdf78b7d99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Check Out')])[2]</value>
      <webElementGuid>90d97700-12d9-42c1-8c4f-dc18673421fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/following::a[2]</value>
      <webElementGuid>89d9e90c-b1bd-48ca-bc34-c9241d1ac585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIONS'])[1]/following::a[3]</value>
      <webElementGuid>106c2162-e50b-4f8d-a460-a0218d4f4ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Favorites'])[1]/preceding::a[10]</value>
      <webElementGuid>c0d2d118-53f6-4047-a2d9-4aa0e580f8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check Out']/parent::*</value>
      <webElementGuid>b39befb2-92dd-4934-96b9-dd3c93baf1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[46]</value>
      <webElementGuid>69010ab4-3672-4836-9172-91ddc9d8ebf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[3]/div[2]/a</value>
      <webElementGuid>61636d25-827e-4088-9a9c-954638395646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Check Out' or . = 'Check Out')]</value>
      <webElementGuid>4b5d601e-1510-4398-becf-de44c4b18b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
