<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Resend Security Code_txtPassword</name>
   <tag></tag>
   <elementGuidId>2d27d044-5bd0-40ef-8210-cc6b50e6f38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb5caef7-fc7c-4f7e-8157-248a48e49c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>446b4e24-76be-4c6f-a19c-01a06c078908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1e7b6ba2-9cf5-4546-9ff9-26dbbdf5c846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>1506c354-5176-443a-9550-883a0575f7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPassword</value>
      <webElementGuid>fcd55bd9-e9f3-4c13-95fe-e8bb80576840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPassword&quot;)</value>
      <webElementGuid>98b5fcd3-b94c-4ff0-a1cd-4fd9583573d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPassword']</value>
      <webElementGuid>4beb6e75-29ed-4f49-839b-d086d229cb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPassword']/input</value>
      <webElementGuid>34d4d297-1a40-474b-bc61-34c93ca79684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>24ee2065-945e-49f7-8b10-431488d42f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @id = 'txtPassword']</value>
      <webElementGuid>1b06c739-a214-4493-af84-bab461d8fa26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
