<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Close_doctitle_2924</name>
   <tag></tag>
   <elementGuidId>25a1e4c2-caf4-4c8b-9be1-e5c1c7c37ad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doctitle_2924']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#doctitle_2924</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;0049 FSIS Training Manual 2024 (Version1)Dec 16, 2024 UC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02f0ab48-7f42-4144-acac-f8457d9c749d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctitle_2924</value>
      <webElementGuid>c89192ae-1145-4c3f-843e-cf1549fa8458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:0049 FSIS Training Manual 2024 (Version1)Dec 16, 2024 UC DocumentDate:10/14/2025 CheckedInDate:10/14/2025 EmployeeName:Leomar Balet EmployeeNo:53453543</value>
      <webElementGuid>626357b1-c075-4a33-8791-ddbd7ff67648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentProperties(2924, 1036, 1199)</value>
      <webElementGuid>8b2da613-d595-4e04-976e-8d413507cd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4024c14f-6c5a-462a-8d04-c9d84d7ed8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctitle custom-link-color</value>
      <webElementGuid>ffb2af8d-7ea9-495e-aeef-981394854ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0049 FSIS Training Manual 2024 (Version1)Dec 16, 2024 UC</value>
      <webElementGuid>878a0bd2-9f6a-4c6e-bf20-b169bb4a843c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctitle_2924&quot;)</value>
      <webElementGuid>1365ab24-1364-4b5d-b40b-1319b8a4bfd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doctitle_2924']</value>
      <webElementGuid>20458914-4855-4bd2-9486-6d4781919708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-row-2924']/div[2]/a</value>
      <webElementGuid>b5533708-727e-4e27-9cac-77cdccfba309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'0049 FSIS Training Manual 2024 (Version1)Dec 16, 2024 UC')]</value>
      <webElementGuid>1e85c1da-8d29-483a-b297-39883b7c3b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::a[9]</value>
      <webElementGuid>0b5c1b5e-4e72-4a6f-bd3d-206e76a4eaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESCAPE CHARACTERS OPERATOR'])[1]/following::a[9]</value>
      <webElementGuid>cff37f3c-a8ad-4038-a3b4-9ed4d8afd351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similatan, Syndy'])[1]/preceding::a[1]</value>
      <webElementGuid>a75bc5b1-3e7d-486b-8329-7d0ce724c3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0049 FSIS Training Manual 2024 (Version1)Dec 16, 2024 UC']/parent::*</value>
      <webElementGuid>b4782999-145e-4fdb-a654-270d19a8bbc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[21]</value>
      <webElementGuid>05c1f47a-6aaf-42fd-b9a0-e08263fbf4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>2ba897c8-5408-4762-89f3-172f8e154605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doctitle_2924' and @title = 'DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:0049 FSIS Training Manual 2024 (Version1)Dec 16, 2024 UC DocumentDate:10/14/2025 CheckedInDate:10/14/2025 EmployeeName:Leomar Balet EmployeeNo:53453543' and @href = '#' and (text() = '0049 FSIS Training Manual 2024 (Version1)Dec 16, 2024 UC' or . = '0049 FSIS Training Manual 2024 (Version1)Dec 16, 2024 UC')]</value>
      <webElementGuid>9f46e66b-872a-411d-8377-fb61ea0cd94c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
