<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete_btnDisplayLibraryCRUD</name>
   <tag></tag>
   <elementGuidId>aa9de127-eaa3-4427-860d-b6905a10cc87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDisplayLibraryCRUD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnDisplayLibraryCRUD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cae0d1d-8256-4033-b01e-b8a194975e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>b541f712-db2b-42e7-ad07-075c506a174f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDisplayLibraryCRUD</value>
      <webElementGuid>406a2a79-44ec-4bbb-996a-af210e3b2b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDisplayLibraryCRUD&quot;)</value>
      <webElementGuid>b55f76fd-25bb-4614-9472-ad1fecd3e77f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDisplayLibraryCRUD']</value>
      <webElementGuid>585984e1-b5cb-4c7f-8619-5800c8d22e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AIR OPERATOR CERTIFICATE'])[3]/preceding::button[1]</value>
      <webElementGuid>3cf56af3-a2c6-40ed-a7d4-66b536fe5dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>04bd13c9-5e48-4788-bed0-8a2e07262952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnDisplayLibraryCRUD']</value>
      <webElementGuid>0d4cd49d-0aa5-468e-bc29-72b326a564c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
