<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Archive_cboArchiveID</name>
   <tag></tag>
   <elementGuidId>c5bcb9d9-ac40-4756-bb58-e9103adab643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cboArchiveID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cboArchiveID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboArchiveID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a7f0e833-a601-4827-bb8e-075f8e8edc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5bc48167-a8b0-402d-be24-3af05e9bc178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboArchiveID</value>
      <webElementGuid>eeb38a65-79ec-425a-a104-ff5249e2c2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ArchiveId</value>
      <webElementGuid>8a856b7e-59f5-4c8c-a4f6-197904dc294c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ArchivePrimary Finance Archive ( FINANCE)Primary HR Archive ( HR Management)Technical Support PTI ( Empty)Workplace Library ( Empty)Primary IT Archive ( IT)Primary TEST Blob Storage Archive ( TEST Blob Storage(DEV &amp; TEST))local dev ( TEST Blob Storage(DEV &amp; TEST))Primary TEST ENCRYPTION Archive ( TEST ENCRYPTION)Primary FINANCE MANAGEMENT Archive ( FINANCE MANAGEMENT)Primary FINANCE DEP. Archive ( FINANCE DEPARTMENT)Primary HR DEPARTMENT Archive ( HR DEPARTMENT)Primary TEST 0920 Archive ( TEST 0920)CI QA ( FINANCE)CI QA 2 ( FINANCE DEPARTMENT)CI QA 3 ( FINANCE MANAGEMENT)CI QA 4 ( HR DEPARTMENT)CI QA 5 ( TEST Blob Storage(DEV &amp; TEST))CI QA 6 ( HR DEPARTMENT)CI QA 7 ( HR Management)CI QA 8 ( IT)Primary BLOB TESTING Archive ( BLOB TESTING)Primary Anonymous Access Test Archive ( Empty)Anonymous Access Test ( Anonymous Access Test)Primary Vicente  Archive ( Vicente )Primary MIKHAEL Archive ( MIKHAEL)Primary Vicente Syndy 1 Archive ( Vicente Syndy 1)Primary Vicente Syndy 2 Archive ( Vicente Syndy 2)Primary TEST LIBRARY1 Archive ( AIR OPERATOR CERTIFICATE)Primary Workplace Library Archive ( Workplace Library)Primary Human Resource Department Archive ( Human Resource Department)Primary Building Project – Avida Towers Archive ( Building Project – Avida Towers)</value>
      <webElementGuid>b4d36adb-b9af-403e-9cec-47200d44bac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboArchiveID&quot;)</value>
      <webElementGuid>949a4a47-1c55-4493-94cf-8c855639f001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cboArchiveID']</value>
      <webElementGuid>91fce626-4036-428f-b99e-66c8119d2720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-library-crud']/div/div/div[2]/div[3]/select</value>
      <webElementGuid>118f5933-9a36-412f-b477-ce700f682dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archive'])[1]/following::select[1]</value>
      <webElementGuid>b4fb1d5a-1c60-4ee1-9fb8-f6fd898f8116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[3]/following::select[1]</value>
      <webElementGuid>1caf112e-c00a-41fc-9d91-560950d5d167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='InActive'])[1]/preceding::select[1]</value>
      <webElementGuid>387deba3-0394-40f5-8cb9-10ac176bedb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>2f8b4e72-96c1-4531-bf94-e470c2c45721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ca9dc50a-3c1a-4964-8b75-b357f44e224d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cboArchiveID' and @name = 'ArchiveId' and (text() = 'Select ArchivePrimary Finance Archive ( FINANCE)Primary HR Archive ( HR Management)Technical Support PTI ( Empty)Workplace Library ( Empty)Primary IT Archive ( IT)Primary TEST Blob Storage Archive ( TEST Blob Storage(DEV &amp; TEST))local dev ( TEST Blob Storage(DEV &amp; TEST))Primary TEST ENCRYPTION Archive ( TEST ENCRYPTION)Primary FINANCE MANAGEMENT Archive ( FINANCE MANAGEMENT)Primary FINANCE DEP. Archive ( FINANCE DEPARTMENT)Primary HR DEPARTMENT Archive ( HR DEPARTMENT)Primary TEST 0920 Archive ( TEST 0920)CI QA ( FINANCE)CI QA 2 ( FINANCE DEPARTMENT)CI QA 3 ( FINANCE MANAGEMENT)CI QA 4 ( HR DEPARTMENT)CI QA 5 ( TEST Blob Storage(DEV &amp; TEST))CI QA 6 ( HR DEPARTMENT)CI QA 7 ( HR Management)CI QA 8 ( IT)Primary BLOB TESTING Archive ( BLOB TESTING)Primary Anonymous Access Test Archive ( Empty)Anonymous Access Test ( Anonymous Access Test)Primary Vicente  Archive ( Vicente )Primary MIKHAEL Archive ( MIKHAEL)Primary Vicente Syndy 1 Archive ( Vicente Syndy 1)Primary Vicente Syndy 2 Archive ( Vicente Syndy 2)Primary TEST LIBRARY1 Archive ( AIR OPERATOR CERTIFICATE)Primary Workplace Library Archive ( Workplace Library)Primary Human Resource Department Archive ( Human Resource Department)Primary Building Project – Avida Towers Archive ( Building Project – Avida Towers)' or . = 'Select ArchivePrimary Finance Archive ( FINANCE)Primary HR Archive ( HR Management)Technical Support PTI ( Empty)Workplace Library ( Empty)Primary IT Archive ( IT)Primary TEST Blob Storage Archive ( TEST Blob Storage(DEV &amp; TEST))local dev ( TEST Blob Storage(DEV &amp; TEST))Primary TEST ENCRYPTION Archive ( TEST ENCRYPTION)Primary FINANCE MANAGEMENT Archive ( FINANCE MANAGEMENT)Primary FINANCE DEP. Archive ( FINANCE DEPARTMENT)Primary HR DEPARTMENT Archive ( HR DEPARTMENT)Primary TEST 0920 Archive ( TEST 0920)CI QA ( FINANCE)CI QA 2 ( FINANCE DEPARTMENT)CI QA 3 ( FINANCE MANAGEMENT)CI QA 4 ( HR DEPARTMENT)CI QA 5 ( TEST Blob Storage(DEV &amp; TEST))CI QA 6 ( HR DEPARTMENT)CI QA 7 ( HR Management)CI QA 8 ( IT)Primary BLOB TESTING Archive ( BLOB TESTING)Primary Anonymous Access Test Archive ( Empty)Anonymous Access Test ( Anonymous Access Test)Primary Vicente  Archive ( Vicente )Primary MIKHAEL Archive ( MIKHAEL)Primary Vicente Syndy 1 Archive ( Vicente Syndy 1)Primary Vicente Syndy 2 Archive ( Vicente Syndy 2)Primary TEST LIBRARY1 Archive ( AIR OPERATOR CERTIFICATE)Primary Workplace Library Archive ( Workplace Library)Primary Human Resource Department Archive ( Human Resource Department)Primary Building Project – Avida Towers Archive ( Building Project – Avida Towers)')]</value>
      <webElementGuid>6a244d7a-0411-4ad0-b967-bc85f190c74c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
