<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Close_doctitle_2974</name>
   <tag></tag>
   <elementGuidId>2c4414bb-7055-49ed-a3d0-6eaf384adc42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doctitle_2974</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doctitle_2974']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;dump1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f12a26b-1a34-477c-b6b3-74ebcc9cf505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctitle_2974</value>
      <webElementGuid>1469ebfd-5d67-497a-adcc-db4aa5f177d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:dump1 keywords sample for katalon automation DocumentDate:11/12/2025 CheckedInDate:11/12/2025 EmployeeName:Dennis John Tonzo EmployeeNo:123654</value>
      <webElementGuid>8a77bd62-538a-4df4-a8db-3ad4f0d12b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentProperties(2974, 1036, 1199)</value>
      <webElementGuid>fd700507-476a-4091-b623-ba7fec895345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4636bc51-1fe0-40f0-8192-211899e2b057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctitle custom-link-color</value>
      <webElementGuid>6233c8c6-10cd-487a-ae3e-764f0f03521e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dump1</value>
      <webElementGuid>8d738aaa-4cd0-4c22-826e-c9aedac10f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctitle_2974&quot;)</value>
      <webElementGuid>925fad7d-530c-47e7-91c2-13f051ea8498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doctitle_2974']</value>
      <webElementGuid>c7d3bffd-ded8-46c1-aba6-f47ec10571fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-row-2974']/div[2]/a</value>
      <webElementGuid>a0d31b98-6fd8-47c2-995e-d27a7a5399e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'dump1')]</value>
      <webElementGuid>aac37b9e-61c3-4bf3-98a9-3c1f309bb5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::a[9]</value>
      <webElementGuid>bcd903ff-40cb-4f87-b9aa-f2f9f606311d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESCAPE CHARACTERS OPERATOR'])[1]/following::a[9]</value>
      <webElementGuid>375308f6-e511-4b82-9f40-a3c56a6196df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similatan, Syndy'])[1]/preceding::a[1]</value>
      <webElementGuid>01f4083a-f8af-40ec-b7f9-87dfe53c091e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dump1']/parent::*</value>
      <webElementGuid>4f66313a-b8fc-40f8-8310-69e132f44487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[21]</value>
      <webElementGuid>be88f0d0-5499-44bc-82de-316337f6e9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>c34cecf6-07f3-45f7-9d54-1c5d9f8fa3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doctitle_2974' and @title = 'DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:dump1 keywords sample for katalon automation DocumentDate:11/12/2025 CheckedInDate:11/12/2025 EmployeeName:Dennis John Tonzo EmployeeNo:123654' and @href = '#' and (text() = 'dump1' or . = 'dump1')]</value>
      <webElementGuid>66524559-7b89-4712-8315-e79db8280cd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
