<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manalo, Nicole_doctitle_2978</name>
   <tag></tag>
   <elementGuidId>035936d0-f2c0-4641-975f-ba9e071105ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doctitle_2978</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doctitle_2978']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#doctitle_2978</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fcbd519e-ce15-4266-838c-d4a5e88b0048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctitle_2978</value>
      <webElementGuid>9eba6997-4137-4635-b99f-0fa9ddbeac20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/12/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123</value>
      <webElementGuid>66c862f6-d5a8-4791-b9cb-a83ef7dee39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentProperties(2978, 1036, 1199)</value>
      <webElementGuid>b392aa66-ea3b-47a2-8809-c543d81946b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4032fb93-139c-4f58-95a1-87e1df2be177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctitle custom-link-color</value>
      <webElementGuid>20978fd2-adda-45d8-87bd-341e4d97ecfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>3aeff7b7-3188-4381-b819-91e17de857d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctitle_2978&quot;)</value>
      <webElementGuid>30218b32-2e0e-4f1d-9a9a-e4583659dfe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doctitle_2978']</value>
      <webElementGuid>2879d65d-07d1-4287-9b8e-09a7dab3f14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-row-2978']/div[2]/a</value>
      <webElementGuid>38a27954-ebd4-4621-ae63-33853cf94b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'test')]</value>
      <webElementGuid>04f0928a-c1cc-4333-8537-47dea32a876a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manalo, Nicole'])[2]/following::a[1]</value>
      <webElementGuid>10a25ebf-42a0-4f05-9cb6-26589ddd34bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similatan, Syndy'])[8]/preceding::a[1]</value>
      <webElementGuid>0691dbed-ce1f-4367-957d-87ae705b30d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>efbc716f-77fe-48a6-8ff5-6dbe614fc27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[38]</value>
      <webElementGuid>577c3e14-7799-4800-b7f9-7391e417180b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[2]/a</value>
      <webElementGuid>3f8b1be1-9f6c-4f1c-97dd-e2afc8ffe6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doctitle_2978' and @title = 'DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/12/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123' and @href = '#' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>446de004-d82d-4cb0-b345-c18a9a240a10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
