<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiry Date_ValidTo</name>
   <tag></tag>
   <elementGuidId>fa733ef4-f4a5-4584-ab7b-ca308945f123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValidTo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValidTo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ValidTo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59e8a17e-9b83-4c1c-87c4-c879dd8eaa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>8aba1046-f0a7-4f75-a2bb-d4d6c5880d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValidTo</value>
      <webElementGuid>9d9e0184-564c-4764-9d5f-43700c1901aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValidTo</value>
      <webElementGuid>d322b2ce-018e-4c8c-a548-36166482a65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>9f6000c7-01c2-48ab-8032-7a9109a47867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2030-11-13</value>
      <webElementGuid>ca60171e-a654-44f9-a2e6-bd958c39766c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9c24b215-dd45-4e0e-b919-9cc61c601cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValidTo&quot;)</value>
      <webElementGuid>cc43bbce-8fac-4c5c-830e-5ba380f6e2a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValidTo']</value>
      <webElementGuid>dd6768b7-d021-43e6-82d1-86f0e8c4cee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div[5]/div/input</value>
      <webElementGuid>631d7475-e130-49db-8222-19b4d5bc075d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[5]/div/input</value>
      <webElementGuid>c600ecc9-c53b-48f5-9e41-88c080409e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ValidTo' and @name = 'ValidTo' and @type = 'date']</value>
      <webElementGuid>369ef440-47d7-479f-a099-7c7128e13cb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
