<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Document Date_ValidFrom</name>
   <tag></tag>
   <elementGuidId>3e9d493d-ae2c-4972-b92b-eabba8a1b5df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValidFrom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValidFrom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ValidFrom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>577fd123-a222-4dba-b9ac-4c725b08db50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>01dc53cb-c845-4b8f-9531-b16494ebdc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValidFrom</value>
      <webElementGuid>a8cc6063-fdd1-46c7-bc4d-468b69bba646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValidFrom</value>
      <webElementGuid>b2625b1a-e141-4300-9833-7aa31be066de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4e61cdf5-977a-4d39-a705-33844e6a892b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2025-11-12</value>
      <webElementGuid>88229036-49e3-49ee-93e0-d3fb6692c5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>487ad275-1a89-44c2-808e-e862cc165cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValidFrom&quot;)</value>
      <webElementGuid>ab02f94f-6acb-44e4-8fc1-e3626669f2ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValidFrom']</value>
      <webElementGuid>df49ea45-a738-41c9-b4ed-ddce6bd48d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div[4]/div/input</value>
      <webElementGuid>4555aa75-e1d5-444a-9772-755804cd4328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[4]/div/input</value>
      <webElementGuid>20bb8b18-3302-4081-96ce-ec62fdaaeaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ValidFrom' and @name = 'ValidFrom' and @type = 'date']</value>
      <webElementGuid>cbb062fc-c01f-4cac-9661-2f291aa3afab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
