<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EmployeeNo_index_EmployeeNo</name>
   <tag></tag>
   <elementGuidId>16c01e1f-8cfa-4635-8df5-6f860e7307ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;index_EmployeeNo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='index_EmployeeNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;index_EmployeeNo&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae0580af-1782-4d8b-a7bc-419589fe31d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f77ab784-68b3-48d7-9a40-2f3130eb9c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>32064cdc-1c43-4020-a0d8-315f9167a0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>index_EmployeeNo</value>
      <webElementGuid>07740d0a-14b0-4fc0-a8cc-80678e3132dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123654</value>
      <webElementGuid>01bc95d3-fe46-43aa-bf50-73f45599f586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placeholder_indexlist_edit&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>b322269a-6ea7-496d-8dbb-203528038b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='index_EmployeeNo']</value>
      <webElementGuid>9ed4a2a7-3f7c-4d68-a63d-4b927e0bbd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='placeholder_indexlist_edit']/div[2]/div/input</value>
      <webElementGuid>ed9799bd-e16f-492b-9479-d0e15032fddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/input</value>
      <webElementGuid>c3d122ab-5424-4b0c-b044-8a5f603a44a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'index_EmployeeNo']</value>
      <webElementGuid>ab4d4892-390f-4a52-ad17-524b69901065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
