<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Katalon Add Item Test_fa fa-eye custom-th_b4e0b0</name>
   <tag></tag>
   <elementGuidId>8a500dd1-a2f2-41e7-a575-40c7499abff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-dsitems-forusers']/div/div[2]/ul/li/div/div[3]/div/a[5]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-eye.custom-theme-color-icon-gray1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d64680c7-f9f1-4f30-acb9-c43e8928742b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye custom-theme-color-icon-gray1</value>
      <webElementGuid>cd7b75f9-eb43-4dc5-a650-b6671befd7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-dsitems-forusers&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body p-0&quot;]/ul[@class=&quot;todo-list&quot;]/li[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;card-tools float-right&quot;]/a[5]/i[@class=&quot;fa fa-eye custom-theme-color-icon-gray1&quot;]</value>
      <webElementGuid>f2ebf171-e974-478a-8b78-b5fdc8a549a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-dsitems-forusers']/div/div[2]/ul/li/div/div[3]/div/a[5]/i</value>
      <webElementGuid>e4c971ac-ceec-451e-9db3-09e18c381765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/i</value>
      <webElementGuid>b85809b4-1e05-4066-92a7-cbb98361697f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
