<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Name_DSIName</name>
   <tag></tag>
   <elementGuidId>4d93f6b0-4d77-481b-8d6e-ee3c2fbd80d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DSIName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DSIName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Item Name:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f8027ed-db5a-49c5-8726-425cf7f1cfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2307a14d-f260-4b63-b34b-bc73a4d94628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>250e457e-ce67-42e0-86c5-fef5f07c5c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DSIName</value>
      <webElementGuid>be1fff3d-8847-43ad-bebf-7f68ba766d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DSIName</value>
      <webElementGuid>fb78a059-958b-41ec-9324-d715fba42724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DSIName&quot;)</value>
      <webElementGuid>35c21037-4a10-4439-b392-e9e7c40fa71c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DSIName']</value>
      <webElementGuid>26203f5c-549f-4021-812a-44eb494008de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-documentsetitem-crud']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>2660fd51-056d-43aa-be35-ce135d49faba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>976caaa9-6a25-4966-ad90-1906bb05ab03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DSIName' and @name = 'DSIName']</value>
      <webElementGuid>5a8ecaad-98c2-4540-b119-8cdabf5af643</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
