<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_DSIDescription</name>
   <tag></tag>
   <elementGuidId>4e297f12-5dff-41ed-a664-a536a01ef131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DSIDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DSIDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44b4783d-1539-4940-a063-c22e9f477a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c0f08d45-b4f5-41e1-bc5f-bd0ab899af9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f832606-3625-47d0-ab47-ddfa52f73823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DSIDescription</value>
      <webElementGuid>70f94a6e-e171-46d6-bee8-0ebae4d67b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DSIDescription</value>
      <webElementGuid>b8bec63a-d404-4bd2-8de7-51bf8163589b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DSIDescription&quot;)</value>
      <webElementGuid>ced26356-f03f-4b8e-92f3-d6fb111a553e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DSIDescription']</value>
      <webElementGuid>863c9f21-5021-4ac6-aabf-399cfeb30be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-documentsetitem-crud']/div/div/div[2]/div[3]/input</value>
      <webElementGuid>be2cb4b9-4991-4c61-b641-8d5370fad610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ec6431df-e0bf-402f-8bf9-d8eec8db5839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DSIDescription' and @name = 'DSIDescription']</value>
      <webElementGuid>912f8089-f8af-4224-86ac-9c8ace8b3495</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
