<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Validity_Validity</name>
   <tag></tag>
   <elementGuidId>ca67552e-6c2f-42cd-8634-1c8a9d8c4083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Validity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Validity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Validity:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c91d9295-1f07-47b1-bb00-eebb848767a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>019cedb3-c379-4df2-a564-146a3ba1386c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Validity</value>
      <webElementGuid>7a604d8f-8b3b-4ccd-b3dd-6692cdc33989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Validity</value>
      <webElementGuid>300f4496-557b-42e1-a1b9-17ed3ef4a271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Annual
                            Monthly
                            Optional
                            Permanent
                            Quarterly
                            SemiAnnual
                        </value>
      <webElementGuid>a578231c-ad6c-4900-9947-2e0edbf7a4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Validity&quot;)</value>
      <webElementGuid>99ecfb56-f135-4f2c-ac2d-c3da2a8f33d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Validity']</value>
      <webElementGuid>99627995-45b5-4f23-a88c-da755d155e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-documentsetitem-crud']/div/div/div[2]/div[5]/select</value>
      <webElementGuid>7ffa531e-06c2-4ef9-af67-ddaa6cba3560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validity:'])[1]/following::select[1]</value>
      <webElementGuid>d74c0b9b-6279-48b0-9a8c-7ed19007b25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annotation:'])[1]/following::select[1]</value>
      <webElementGuid>f35b64ac-048f-439b-a7e3-945ca9031489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DocumentType:'])[1]/preceding::select[1]</value>
      <webElementGuid>e9abce3a-e475-4a86-adcd-3a778d4eb2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library:'])[1]/preceding::select[2]</value>
      <webElementGuid>b80c4442-abd5-4050-b4b1-81847d19cd3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>59d4f035-2c88-4665-818f-c52dbf481bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Validity' and @name = 'Validity' and (text() = '
                            Annual
                            Monthly
                            Optional
                            Permanent
                            Quarterly
                            SemiAnnual
                        ' or . = '
                            Annual
                            Monthly
                            Optional
                            Permanent
                            Quarterly
                            SemiAnnual
                        ')]</value>
      <webElementGuid>8c9f15ab-c386-4155-87c9-dec684e12a07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
