<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Folder_DocumentFolderIDDSI</name>
   <tag></tag>
   <elementGuidId>57292109-73b8-4c29-8836-cb034dc4aa44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DocumentFolderIDDSI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DocumentFolderIDDSI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DocumentFolderIDDSI</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1923964f-7f7a-462e-9ee5-de2102f309b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DocumentFolderID</value>
      <webElementGuid>f683df2f-4b4c-4e98-8b3c-c013d84578f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DocumentFolderIDDSI</value>
      <webElementGuid>2fb0366c-a90c-41eb-8bff-046d007079df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6c294145-83c7-48d8-9c2f-129267bdbd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A. 201 FilesOffice Files</value>
      <webElementGuid>71ce9600-1a35-42da-be5a-51e654d8627e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DocumentFolderIDDSI&quot;)</value>
      <webElementGuid>1b6a5d1f-7828-42ff-b36c-650d9912a139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DocumentFolderIDDSI']</value>
      <webElementGuid>7f8ba95f-2cb9-4772-8c3d-0c91da2825eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-documentsetitem-crud']/div/div/div[2]/div[8]/select</value>
      <webElementGuid>38617bce-acda-426b-ab8f-ad2685d1ade2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folder:'])[1]/following::select[1]</value>
      <webElementGuid>dbcf2da6-bdce-4b08-90c9-d0937fe42ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library:'])[1]/following::select[2]</value>
      <webElementGuid>34d0b185-0d17-47c4-b0ae-078bd38d1b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>884e85eb-13bb-46a3-8320-5793a357d925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>ab5d94f0-4e51-451e-b187-8bf88a1c07c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>90c9efd3-7a9b-40bd-84ef-0ae44aa0fb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'DocumentFolderID' and @id = 'DocumentFolderIDDSI' and (text() = 'A. 201 FilesOffice Files' or . = 'A. 201 FilesOffice Files')]</value>
      <webElementGuid>87c1109b-6709-4667-b953-949e15d9a634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
