<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Library_LibraryIDDSI</name>
   <tag></tag>
   <elementGuidId>f9f4f7fe-1315-425c-93db-aaa3fb4f0877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LibraryIDDSI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LibraryIDDSI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#LibraryIDDSI</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1b552b21-97d5-4f01-8d71-e1833ac01135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LibraryID</value>
      <webElementGuid>90240274-c00d-427f-98bb-3b0e18bb0f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LibraryIDDSI</value>
      <webElementGuid>010278b1-fa80-4c23-aa0c-444a450ac560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ab384d04-aa6e-4431-9799-c4bd80c50c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Building Project – Avida TowersFINANCEHuman Resource Department</value>
      <webElementGuid>4452563d-e48f-4bab-b0d5-95e4ff9d9a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LibraryIDDSI&quot;)</value>
      <webElementGuid>2dfb0ee9-914a-45cd-989d-b2b9a2bcd290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LibraryIDDSI']</value>
      <webElementGuid>eb543ff6-f0f8-46ef-8c01-d22654f7b84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-documentsetitem-crud']/div/div/div[2]/div[7]/select</value>
      <webElementGuid>d58442ac-a026-4b3d-9796-912b777ef79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library:'])[1]/following::select[1]</value>
      <webElementGuid>c3ab3c80-ea62-4b33-a0f4-0b1e0b03a7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DocumentType:'])[1]/following::select[2]</value>
      <webElementGuid>30e7e964-26e1-4427-b039-1ac197ea28ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folder:'])[1]/preceding::select[1]</value>
      <webElementGuid>6d74e385-1ac9-4400-aeb0-598a67e1ef0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[2]</value>
      <webElementGuid>de55c4c2-1490-422e-8307-84897faf5403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>b24c99c0-1b51-4d6a-a847-f08a0ec64e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'LibraryID' and @id = 'LibraryIDDSI' and (text() = 'Building Project – Avida TowersFINANCEHuman Resource Department' or . = 'Building Project – Avida TowersFINANCEHuman Resource Department')]</value>
      <webElementGuid>2e89c19f-84e2-4fb4-898c-acdf7fc916e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
