<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DocumentType_DocumentTypeIDDSI</name>
   <tag></tag>
   <elementGuidId>2ce24f8e-f668-405b-abef-c532a70e9de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DocumentTypeIDDSI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DocumentTypeIDDSI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DocumentTypeIDDSI</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c0627800-1e7b-4eb7-aa4e-3ff361abff00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DocumentTypeIDDSI</value>
      <webElementGuid>dced05aa-7a5f-45b7-8268-dbdd154c0235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>632ae8d3-81b2-4dbf-b071-0b591627d686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DocumentTypeID</value>
      <webElementGuid>c67643ff-4d92-46b9-82e4-027e508a61b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check VoucherCORPORATE CHECKEMPLOYEE 201Expense VoucherGeneral DocumentPetty CashPoliciesPolicyPurchase Order</value>
      <webElementGuid>a6658cec-443a-4e4e-b840-6d202954f490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DocumentTypeIDDSI&quot;)</value>
      <webElementGuid>14b701c6-eda4-44fa-87fc-f93fc57c0c16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DocumentTypeIDDSI']</value>
      <webElementGuid>e8cd0fe4-cf7e-4702-8186-1fed73ce5d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-documentsetitem-crud']/div/div/div[2]/div[6]/select</value>
      <webElementGuid>f756c28f-f1c7-4d79-847a-4b75e90edb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DocumentType:'])[1]/following::select[1]</value>
      <webElementGuid>bd60df92-206d-41bc-b6da-489f4f1c58c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validity:'])[1]/following::select[2]</value>
      <webElementGuid>a4e0610d-ad7b-44f3-8c86-e2aceacdc1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library:'])[1]/preceding::select[1]</value>
      <webElementGuid>07659c41-1e01-44dd-8bf4-7323f3a74044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folder:'])[1]/preceding::select[2]</value>
      <webElementGuid>4310525c-a6df-412d-9603-7dd66e3a2473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>593b2203-2c16-4a96-a9aa-1c4cc3797b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DocumentTypeIDDSI' and @name = 'DocumentTypeID' and (text() = 'Check VoucherCORPORATE CHECKEMPLOYEE 201Expense VoucherGeneral DocumentPetty CashPoliciesPolicyPurchase Order' or . = 'Check VoucherCORPORATE CHECKEMPLOYEE 201Expense VoucherGeneral DocumentPetty CashPoliciesPolicyPurchase Order')]</value>
      <webElementGuid>db79ccb6-825a-4eb3-9625-ee94d642a0a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
