<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preview_custom-link-color</name>
   <tag></tag>
   <elementGuidId>bbb62e53-86d7-4e6e-8c20-579e6131076b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='LoadDownloadPartialViewSingleFile(2972)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dadownload_21128 > div.col-sm-8 > a.custom-link-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Folder View&quot;i >> internal:role=link[name=&quot;Download&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62ac894e-7fd6-4146-ac70-4e798ae030ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3292e902-61a6-4d86-ad5e-02398abfc551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-link-color</value>
      <webElementGuid>0b9bfedd-e357-4716-865c-b83520f77740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>LoadDownloadPartialViewSingleFile(2972)</value>
      <webElementGuid>5a81887e-a6b0-48dd-b6b3-2ee42d6ede74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>60863474-0dda-4e3c-ad1d-56be4b0ac477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-document-properties-container&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@id=&quot;dadownload_21128&quot;]/div[@class=&quot;col-sm-8&quot;]/a[@class=&quot;custom-link-color&quot;]</value>
      <webElementGuid>9cb4ff13-5665-41fb-8db8-f71ec1a7839e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='LoadDownloadPartialViewSingleFile(2972)']</value>
      <webElementGuid>b49cb50e-0ef4-4875-8bfa-24d978859a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dadownload_21128']/div[2]/a</value>
      <webElementGuid>4e3df7c8-1fd5-4b12-b94a-fc3c0b53ed57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[2]</value>
      <webElementGuid>986f6297-639d-4ab5-971f-cffc367e898b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/following::a[1]</value>
      <webElementGuid>b7c29135-4509-44f0-afc9-d91df3764b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIONS'])[1]/following::a[2]</value>
      <webElementGuid>06246caa-49ef-4eec-87f9-53ea7beb479f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Favorites'])[1]/preceding::a[11]</value>
      <webElementGuid>0da253a7-c5b7-454f-affb-4d7997d35271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>07dde8d2-78c5-4f77-9fa9-44de0db38997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[41]</value>
      <webElementGuid>3e19bb71-73a8-4563-82df-5aa7c90ca495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div[2]/a</value>
      <webElementGuid>e75ccb70-ccce-4e65-8ec2-4cab11c451be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>64e453ff-4b70-4f02-8aef-1c26af4f28a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
