<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_Keywords</name>
   <tag></tag>
   <elementGuidId>2d440dcc-8d9e-4448-ad49-4a7a0b6bbdc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Keywords</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Keywords']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search documents&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2ea651a-aaa5-42e9-94a9-bae695eaa478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>searchAutoComplete</value>
      <webElementGuid>22c7bafb-32ea-47e2-b02a-23119d83c71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3c435c0f-3491-4491-b7c5-a60593893e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Keywords</value>
      <webElementGuid>aaa916d6-8d1f-4fd9-a467-7b41f8d06a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchText</value>
      <webElementGuid>0290c3ef-ee2f-4b01-b437-3aaccf0ab356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search documents</value>
      <webElementGuid>86e18217-e425-4ad1-a75d-d4c22ab39376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77a9b088-a23f-4af5-a5ae-92ba1f6baebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Keywords&quot;)</value>
      <webElementGuid>e2021237-26dc-4c6e-b8a7-a4f2f9c78570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Keywords']</value>
      <webElementGuid>690a9c65-83b7-4101-aa20-0457f8cca23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-search-filters']/div/div[2]/div/input[2]</value>
      <webElementGuid>8ab66e06-3361-490c-bfe1-8863cca9a1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>cb729b9a-8e9f-4c7d-9278-cc87b236256f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Keywords' and @name = 'SearchText' and @placeholder = 'Search documents' and @type = 'text']</value>
      <webElementGuid>b61ba9c4-626b-4cc0-ae1d-9ea505385fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
