<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preview_custom-link-color</name>
   <tag></tag>
   <elementGuidId>98917710-bd69-4b45-9596-6a096fd74a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='UnlockDocument(2975)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Unlock Document&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80b64211-4643-46f0-baa5-fe5f13054f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>70c29fcc-0384-455a-8d5f-883eb69e618c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-link-color</value>
      <webElementGuid>69f59717-b2f2-4882-aeca-fa91cd9900ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>UnlockDocument(2975)</value>
      <webElementGuid>6429da91-73b4-4a6d-9117-f6f9519cc557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Unlock Document</value>
      <webElementGuid>71c041fc-adcc-4390-85e4-86f5849e53a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-document-properties-container&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@id=&quot;dapreview_21128&quot;]/div[@class=&quot;col-sm-10&quot;]/a[@class=&quot;custom-link-color&quot;]</value>
      <webElementGuid>add7659d-7fcb-4481-be1e-81f56176df5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='UnlockDocument(2975)']</value>
      <webElementGuid>3fbffbde-48fc-4aeb-8a97-257f996f98b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dapreview_21128']/div[2]/a)[3]</value>
      <webElementGuid>e3002400-6375-4fce-b9e8-13f0bba478e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Unlock Document')]</value>
      <webElementGuid>f59f0e84-5b5c-4694-8c84-2481303110a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/following::a[2]</value>
      <webElementGuid>05453865-23c7-46d2-8508-678800dd85fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIONS'])[1]/following::a[3]</value>
      <webElementGuid>27ecb8b7-23b1-432b-81fd-70a8437de347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Favorites'])[1]/preceding::a[11]</value>
      <webElementGuid>a311e57e-b759-4138-8e43-816a2d01c671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unlock Document']/parent::*</value>
      <webElementGuid>d8caaecb-e624-495f-9c44-791d7378b783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[46]</value>
      <webElementGuid>8df47078-c91e-4de6-9527-8aa5ac6fa001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[3]/div[2]/a</value>
      <webElementGuid>7aa3977e-c93c-4ce1-832e-27b7d71c809d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Unlock Document' or . = ' Unlock Document')]</value>
      <webElementGuid>e30147e3-0ca0-4bf7-88ec-f785501d44a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
