<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manalo, Nicole_doctitle_2980</name>
   <tag></tag>
   <elementGuidId>38a9130f-4d78-446c-a161-427d0f94c449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doctitle_2980']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#doctitle_2980</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/13/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3d62e9a-c03f-4236-91ba-1b62ac7a3be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctitle_2980</value>
      <webElementGuid>c640e2ed-4ddd-48c9-b379-50f3cac7fa27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/13/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123</value>
      <webElementGuid>f396b524-b69f-43f9-9841-e17f5eab2732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentProperties(2980, 1036, 1199)</value>
      <webElementGuid>7ac0fa93-e9bd-4767-91e8-46d27752a53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4d1905d3-5a02-4844-b196-f255c01d7eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctitle custom-link-color</value>
      <webElementGuid>963e4fc0-1305-44aa-bf85-e9487d5f6ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>d292e71c-55cd-4990-9396-140d6d0d91a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctitle_2980&quot;)</value>
      <webElementGuid>2a228485-d2b0-4e87-92e8-22bf0a272628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doctitle_2980']</value>
      <webElementGuid>969661ef-2506-49f8-9bc2-bcee971b0c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-row-2980']/div[2]/a</value>
      <webElementGuid>bc8143a5-96aa-46a7-9684-22803366e36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'test')])[2]</value>
      <webElementGuid>b79f90b1-83e7-4881-aecc-edd5b72b9052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manalo, Nicole'])[2]/following::a[1]</value>
      <webElementGuid>5efb5f44-604c-45f2-8d4f-3dd0424366e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similatan, Syndy'])[8]/preceding::a[1]</value>
      <webElementGuid>e296f121-252f-4c3e-9e88-e7335f77371c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>cfb5536c-4009-4eed-92a1-60229bb24d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[38]</value>
      <webElementGuid>36caab70-2c8f-453a-8bd3-699b7eef3c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[2]/a</value>
      <webElementGuid>4b85ea5c-bb91-4fac-a60b-5984093906c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doctitle_2980' and @title = 'DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/13/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123' and @href = '#' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>2c6062c7-a415-43a4-bd85-7d089936ab1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
