<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manalo, Nicole_doctitle_2980</name>
   <tag></tag>
   <elementGuidId>896b209f-12dd-45b9-bfda-c699cffd759e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='doctitle_2980']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#doctitle_2980</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/13/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9b79ebb-cb88-4f53-b700-629cec6a6ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doctitle_2980</value>
      <webElementGuid>c90b3bd5-3414-4e66-85f8-e0d321234532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/13/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123</value>
      <webElementGuid>03b8f2d5-017b-410d-bcb8-769a598135da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentProperties(2980, 1036, 1199)</value>
      <webElementGuid>88b89017-acf1-4509-9238-c6e08170ef3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9a464334-794e-493e-a984-37df74533b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>doctitle custom-link-color</value>
      <webElementGuid>f05582dd-8997-4ee0-b96d-f94638b30fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>909f543d-528b-45c3-8b9e-8bcf30ab10bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doctitle_2980&quot;)</value>
      <webElementGuid>adcbfa0b-5e91-4e1c-bc80-4c9742d73b46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='doctitle_2980']</value>
      <webElementGuid>6329a338-793a-4107-a9ce-780ec926ff07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-row-2980']/div[2]/a</value>
      <webElementGuid>54de463d-099c-4009-b92d-2dd596c2d47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'test')])[2]</value>
      <webElementGuid>ca16593b-f25c-4918-84a1-4a6851e45525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manalo, Nicole'])[2]/following::a[1]</value>
      <webElementGuid>375fde57-487b-4709-b967-0fbabb82baec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similatan, Syndy'])[8]/preceding::a[1]</value>
      <webElementGuid>4280e141-0372-4956-93fc-254c5bc9d41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>b41194df-7277-4bc4-af1b-8ba0dd0aedde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[38]</value>
      <webElementGuid>594994a4-bb39-4bba-9872-d36aed008372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[2]/a</value>
      <webElementGuid>6ebb3792-859e-4c05-bc23-7110b7f05c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'doctitle_2980' and @title = 'DocumentType:EMPLOYEE 201 DocumentFolder:A. 201 Files CheckedInBy:Similatan, Syndy DocumentTitle:test test case check in testing DocumentDate:11/04/2025 CheckedInDate:11/13/2025 EmployeeName:Dennis John Tonzo EmployeeNo:12369123' and @href = '#' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>a6cfe226-51dc-4496-a497-67ba8b1bc336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
