<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preview_custom-link-color</name>
   <tag></tag>
   <elementGuidId>c4d06c11-c726-4a84-8c58-003634802f8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='DisplayDocumentAccessPassRequestModal(2980);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#darequest_21128 > div.col-sm-8 > a.custom-link-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Request&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eee0680c-9629-4e01-a0c6-23c081e94773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cd2e3cf0-5c70-40ea-90e3-961569a9d76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-link-color</value>
      <webElementGuid>4023cdf4-c732-4b5a-ad2c-ee3bd7dec566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisplayDocumentAccessPassRequestModal(2980);</value>
      <webElementGuid>4cbea2bf-f462-4ad7-893d-7d1fc6f35cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>1ba87437-36ee-4376-8568-459d0cbe893f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;darequest_21128&quot;)/div[@class=&quot;col-sm-8&quot;]/a[@class=&quot;custom-link-color&quot;]</value>
      <webElementGuid>f9dca3ae-7dc7-42c4-87ff-e61aa4b292c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='DisplayDocumentAccessPassRequestModal(2980);']</value>
      <webElementGuid>8f104a09-b8f8-4c22-8fd0-9b75dd80f1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='darequest_21128']/div[2]/a</value>
      <webElementGuid>dd4cd9c3-cb33-4bb1-8857-b6d2fee69744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Request')])[2]</value>
      <webElementGuid>1d28533c-6cbb-4d18-9f06-497810c79826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/following::a[8]</value>
      <webElementGuid>42511615-604c-4f67-aaf6-4bd75a3ead08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIONS'])[1]/following::a[9]</value>
      <webElementGuid>e1e64957-719d-4acd-bd3b-9ff523531c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Favorites'])[1]/preceding::a[4]</value>
      <webElementGuid>a5124b96-1411-4247-9e36-8ceb656f3c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request']/parent::*</value>
      <webElementGuid>e9216280-9603-4121-bbb1-c342f3408321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[52]</value>
      <webElementGuid>9bce2a2e-303d-4e1e-9539-21d9a4e89fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div[4]/div[2]/a</value>
      <webElementGuid>198c4a9d-88c6-427a-9cdb-af7f10ae6770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Request' or . = 'Request')]</value>
      <webElementGuid>d9a26726-2dda-4260-8862-7f198f894932</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
