<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Download_userAcls</name>
   <tag></tag>
   <elementGuidId>9a728494-facb-4814-996d-784484d6fbb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userAcls']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userAcls&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Download&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c66d485-186b-478a-9bde-50a021e552bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e0bb60a0-db9b-4e3a-a878-655ea331f278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userAcls</value>
      <webElementGuid>8105dd2e-6cb8-48d5-ac71-21c0251fa149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Document_DownloadCopy</value>
      <webElementGuid>80731995-fe7a-4c61-87a3-442b6379c355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridResourceGroupACLCategory&quot;)/tbody[1]/tr[@class=&quot;clickable-row&quot;]/td[2]/input[1]</value>
      <webElementGuid>db5d0bd3-60b6-4c9a-a9be-8034da70baf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userAcls']</value>
      <webElementGuid>d14737db-8a86-4e48-a241-6f3a811380ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridResourceGroupACLCategory']/tbody/tr/td[2]/input</value>
      <webElementGuid>5b2acc03-f2c9-4e43-bdd8-b807cd794f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>b31e763e-1452-414c-a4ca-c13e486725ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'userAcls']</value>
      <webElementGuid>a6970988-cedc-4d9c-ada5-be81c47b8dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
