<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiry Date_ValidTo</name>
   <tag></tag>
   <elementGuidId>a1cd6b1b-801e-499c-9ff1-afcacaa353c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValidTo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValidTo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ValidTo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43cf54d6-4ac1-4400-86ab-fff07bcff521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ed821e02-2412-46f0-a013-b83addba1d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValidTo</value>
      <webElementGuid>3219cf00-9141-47ae-be07-4b8062a3084a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValidTo</value>
      <webElementGuid>33f7909d-9a0b-4157-8db7-8fbabcd05393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>eeb0fcc5-249f-4fdb-8b1e-8205863a623a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValidTo&quot;)</value>
      <webElementGuid>87b493a7-4b06-4239-a343-2cef720f56e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValidTo']</value>
      <webElementGuid>977a91d6-188e-4849-aef5-5d84c64f0edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div[7]/div/input</value>
      <webElementGuid>73ccfa83-3679-4d64-b234-05a41fc4d9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>d1d9ab19-c4a1-4c7a-8b49-e99f741a3a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ValidTo' and @name = 'ValidTo' and @type = 'date']</value>
      <webElementGuid>1b62dc45-cdd2-4ea4-ad86-8e7260c4e2ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
