<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keywords_Compress</name>
   <tag></tag>
   <elementGuidId>1371ed22-9c33-4652-b1a1-bc2f17063d0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Compress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Compress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Compress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e661378a-f038-4721-a2d2-449ec7975dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Compress</value>
      <webElementGuid>04e7f48c-358c-41fd-b43e-d84419ad3a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Compress</value>
      <webElementGuid>34712ac7-46cf-46af-b9fc-1abc00ffa772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>09e435d9-4d50-44c7-a398-bcb01bdba5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8bd1da4e-b559-43fd-bdc7-253046a2a095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Compress&quot;)</value>
      <webElementGuid>774e1d52-b0bc-45d2-a93d-4b6f258bf5e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Compress']</value>
      <webElementGuid>3b88acf7-ae4e-4919-96f5-c2a101d9a060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div[9]/div/input</value>
      <webElementGuid>181875b1-6d02-4dad-83af-d855add71f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>ac31ad92-386d-4565-bfbd-0db3e3e8ebc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Compress' and @name = 'Compress' and @type = 'checkbox']</value>
      <webElementGuid>d85b3602-7e4a-4c9c-8d6a-e82a9282980e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
