<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Compress_ExtractText</name>
   <tag></tag>
   <elementGuidId>7e0a6cbb-0816-4197-8f80-bf9de9f8657d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExtractText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ExtractText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ExtractText</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdce4cab-9cab-496d-bcdc-0d0c3946a48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExtractText</value>
      <webElementGuid>3f3a63c6-a433-4d9b-b27e-1599f9cd76f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExtractText</value>
      <webElementGuid>d0858749-ec5c-42fc-a98b-30fc8ae5b7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2999880d-812c-4e19-b9c8-8c759b2df3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00d025c7-ad77-4cce-870b-f43bac111fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExtractText&quot;)</value>
      <webElementGuid>4c3158be-0bc8-44a7-bade-cd8fa4c4b319</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExtractText']</value>
      <webElementGuid>83b35595-1861-4e4d-9374-6c6830dd1d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div[10]/div/input</value>
      <webElementGuid>235ebe7b-c359-4df8-9c40-40d8e841be23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>ae4e25ae-a2b2-4fe0-b8b4-d68ca61ed5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ExtractText' and @name = 'ExtractText' and @type = 'checkbox']</value>
      <webElementGuid>7bfaa44c-c42c-4d5b-804d-8095169cf1da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
