<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse File_inputid</name>
   <tag></tag>
   <elementGuidId>dc216f73-8567-4859-83ad-7a2aeac3e888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#inputid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66f870b2-b0ca-47b3-a6a3-50b61b2f938e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>93165382-c349-4b4a-94b0-f46c438245a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputid</value>
      <webElementGuid>422cd94d-2dad-410a-8923-612c4227e30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Filename</value>
      <webElementGuid>064cb751-b4c8-4392-8bc8-d105151c65e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ac1a8c49-9a2b-43c4-a06c-c0eb03da38b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputid&quot;)</value>
      <webElementGuid>9ef075e6-b039-4b46-b512-e57363abcdbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputid']</value>
      <webElementGuid>961361e2-96fe-4b53-bb55-f8cca9c038de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div/div/div/input</value>
      <webElementGuid>dc5507f0-be48-4fc5-9eff-454c8b04759b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>bda5640d-f98a-4c10-ac18-6bb2f3621359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputid' and @name = 'Filename' and @type = 'file']</value>
      <webElementGuid>cb92a3e2-8a37-4d8f-a276-12cde07af2a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
