<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Document Date_ValidFrom</name>
   <tag></tag>
   <elementGuidId>a7e21dad-b8a7-4675-9b0d-f7b53d41e8c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValidFrom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValidFrom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ValidFrom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53158b3c-2f03-49a3-879f-eb8436f8972c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>39675b0e-a6c5-4434-b5ff-99a39577cd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValidFrom</value>
      <webElementGuid>f13f24fe-b572-43e5-88e0-f3a2a37deec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValidFrom</value>
      <webElementGuid>9c3213d2-f9b5-4891-97d2-29b047735a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>2878cf9a-2707-47c8-851d-9296b7db0277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2025-10-30</value>
      <webElementGuid>aa9a43f0-8dc3-4139-a172-67fbdd482895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValidFrom&quot;)</value>
      <webElementGuid>326123be-beba-4503-96a1-58e53c55726f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValidFrom']</value>
      <webElementGuid>c0a33925-d3b6-4dd8-8073-94b4dfdbbe53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div[6]/div/input</value>
      <webElementGuid>a4bc8e2c-fc3e-48df-9de3-2cc9b1542336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>b337191a-2c54-4aed-a426-e799a2328dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ValidFrom' and @name = 'ValidFrom' and @type = 'date']</value>
      <webElementGuid>367b7457-c9b5-40ae-a19e-78c7c21a92d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
