<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EmployeeNo_index_EmployeeNo</name>
   <tag></tag>
   <elementGuidId>126f0813-8cd9-4e6d-97f6-37a4e0369410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;index_EmployeeNo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='index_EmployeeNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;index_EmployeeNo&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20ba85dc-34ec-4b4f-8ac3-8c7f4a05b52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60c157e8-da0c-4a90-bf4c-c542c409e019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fdccbc91-7aa0-4bc3-bb7e-32afbda888f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>index_EmployeeNo</value>
      <webElementGuid>89e99bf0-6520-473e-a51f-1a274f3d8a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placeholder_indexlist&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7b88f62b-0f75-4ce7-bd09-1c6d32595ec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='index_EmployeeNo']</value>
      <webElementGuid>483cd9aa-814c-4aab-8fc6-6a4598dfb4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='placeholder_indexlist']/div[3]/div/input</value>
      <webElementGuid>4736d1dc-c9f2-4314-a5ca-7869b029ae7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[3]/div/input</value>
      <webElementGuid>20e1c6e8-697f-4efb-9a9f-144b5bf3b3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'index_EmployeeNo']</value>
      <webElementGuid>b9a43aea-3b09-4949-b690-2560abe96a4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
