<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Document Type_select2-DocumentType-container</name>
   <tag></tag>
   <elementGuidId>53a2678f-e9a6-4495-b985-3fde3f9cc14f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-DocumentType-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-DocumentType-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Select Document Type&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2363b53-5a27-4135-97a0-171192d20289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>481df4f2-3b4c-428d-8cd4-822941672f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DocumentType-container</value>
      <webElementGuid>0ebac1c6-fc6e-45a9-882c-7ed2a3b7cd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>186b5c6e-5ff2-45aa-992d-289b9209fa46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c11686a-417f-4ea1-b34e-88ca6c9de9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select Document Type</value>
      <webElementGuid>9a98e7d0-d945-4c4a-b342-fc1722d5dcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Document Type</value>
      <webElementGuid>cdc032f1-1d9a-4d7b-9a2f-00b35ec75085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DocumentType-container&quot;)</value>
      <webElementGuid>4b1cf70a-2870-460a-850f-643295c7d9a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-DocumentType-container']</value>
      <webElementGuid>bd74963c-ded8-446b-894d-6db13775d630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div[3]/div/span/span/span/span</value>
      <webElementGuid>20ec1cfe-e385-4c4c-b6a9-08a664786614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Type'])[2]/following::span[4]</value>
      <webElementGuid>f73d16f2-f85a-4af5-bbcf-cb2ef9ea3376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Folder'])[1]/following::span[5]</value>
      <webElementGuid>a678612c-97e7-4624-afac-dc71e34190b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Title'])[1]/preceding::span[3]</value>
      <webElementGuid>86fb8d3a-eeea-4b2f-8bc9-36b351e1e2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[2]/preceding::span[4]</value>
      <webElementGuid>e5c76aca-e805-49cf-a65a-1982a2da09b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>b58d05a5-23d0-45f4-ba10-22104665c45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-DocumentType-container' and @title = 'Select Document Type' and (text() = 'Select Document Type' or . = 'Select Document Type')]</value>
      <webElementGuid>b96ec4a5-c8f1-4053-94b5-d9576a4b61f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
