<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keywords_Keywords</name>
   <tag></tag>
   <elementGuidId>0d5c9b36-b8fe-4928-b8b4-b1afb4db32c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-8 > #Keywords</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Keywords']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;Keywords&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ebb13ed8-812b-422a-8be0-da7ffe774435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ce83c987-fa4a-4da9-a60b-785d06305bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Keywords</value>
      <webElementGuid>1db9c3b7-23c7-40a8-aa40-6b62204a7187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Keywords</value>
      <webElementGuid>cd50b258-d5c6-4e3d-87c4-47c1ff91439b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resize</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>1a69b4bd-0b18-48db-bb47-495668d798c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doc-checkinproperties-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;row mt-2&quot;]/div[@class=&quot;col-sm-8&quot;]/textarea[@id=&quot;Keywords&quot;]</value>
      <webElementGuid>d57b4d6e-234e-4435-ad46-1b80290d12a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Keywords']</value>
      <webElementGuid>3511a42c-28b3-4aba-8e38-c8f9f497a696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='doc-checkinproperties-container']/div[2]/div/div[8]/div/textarea</value>
      <webElementGuid>61d57494-2afa-48ee-8c21-c7301a077fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c65890dc-1019-4699-a5e5-48f1e7d7cb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Keywords' and @name = 'Keywords']</value>
      <webElementGuid>c5153b81-9053-4878-a779-d15165ff68ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
