<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_concat(id(, , select2-DocumentType-resul_e3bcf5</name>
   <tag></tag>
   <elementGuidId>ed6efa87-8e5a-4d1a-9cdd-8fb31d37fb45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-DocumentType-results</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-DocumentType-results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-DocumentType-results</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>ea8d2711-5a1e-4a7e-bb6a-21835f37c6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>0e8d2167-78c3-4bff-8b98-25fd34d6aca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ab750e56-e973-4781-999f-10878ef98f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DocumentType-results</value>
      <webElementGuid>590f2010-76fc-4ea1-8579-c0aa607883f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>73561330-8563-42c9-bd40-79073202bbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47e9b63a-32b3-4e83-8190-ef8e251f61a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Document TypeCheck VoucherCORPORATE CHECKEMPLOYEE 201Expense VoucherGeneral DocumentPetty CashPoliciesPolicyPurchase Order</value>
      <webElementGuid>85622087-df92-4df3-966d-e74eb9c8e108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DocumentType-results&quot;)</value>
      <webElementGuid>bf2ed128-f3d2-4b76-be59-fe46dd7a6633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-DocumentType-results']</value>
      <webElementGuid>7a263ed7-a0e2-4495-ae69-1ba87110ba19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::ul[1]</value>
      <webElementGuid>62d5d664-adb2-43f9-8b60-24796cac5ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>e15eb7ff-718a-4a1e-99f5-4ac2c49d826f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-DocumentType-results' and (text() = 'Select Document TypeCheck VoucherCORPORATE CHECKEMPLOYEE 201Expense VoucherGeneral DocumentPetty CashPoliciesPolicyPurchase Order' or . = 'Select Document TypeCheck VoucherCORPORATE CHECKEMPLOYEE 201Expense VoucherGeneral DocumentPetty CashPoliciesPolicyPurchase Order')]</value>
      <webElementGuid>e92ef463-77e5-4e0c-9d8b-0d9028d83dfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
