<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Document Set Templates  Assignments__bcb9ce</name>
   <tag></tag>
   <elementGuidId>d7f1cbfd-ff64-4eee-9721-0f5301e013c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddSaveTemplate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAddSaveTemplate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#btnAddSaveTemplate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b622fbb1-0447-4133-8fb2-dcdce6397b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm btn-flat</value>
      <webElementGuid>2b3a560f-0882-4f11-a57b-225b7c260715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddSaveTemplate</value>
      <webElementGuid>89eb73dc-bf6a-412c-a487-5437edc31773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddSaveTemplate&quot;)</value>
      <webElementGuid>456aaf96-e824-4952-9c2b-a75e805b1a2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAddSaveTemplate']</value>
      <webElementGuid>096234c7-467f-4351-962e-2ecdc6e71ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Set Templates &amp; Assignments'])[1]//button[1]</value>
      <webElementGuid>29a71c40-133c-4ccc-a11b-b59791b4c95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archive One'])[2]/following::button[1]</value>
      <webElementGuid>522b5887-ff2a-44d9-931c-ec957af8877f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Project - ABC Towers'])[1]/preceding::button[1]</value>
      <webElementGuid>b58a447f-d55f-4f0c-9c6d-bfba77d99bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condo Unit Set - Unit 1001'])[1]/preceding::button[1]</value>
      <webElementGuid>4895aa85-6128-401e-b1b4-d2ec24d75d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>d3c71904-52aa-4320-8ce1-f1be949e4a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnAddSaveTemplate']</value>
      <webElementGuid>4297f4b0-1af6-4627-8c2d-edde9d3d06ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
