<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_DSName</name>
   <tag></tag>
   <elementGuidId>43ea9f89-30c5-4425-9764-78d2daca4658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DSName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DSName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Name:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2341e1e3-1b39-4839-9924-773b0aaba1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3846fb76-e6f0-4c43-b5c0-3500949063c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8cd2bde6-3371-44b6-9519-6acb8c78be23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DSName</value>
      <webElementGuid>69a49cb7-6465-4d9b-a098-341d4ca32c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DSName</value>
      <webElementGuid>8f380541-a1a5-4598-8b05-b4dcc3d21f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DSName&quot;)</value>
      <webElementGuid>193279bd-3310-4378-b507-56c20cb65977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DSName']</value>
      <webElementGuid>831eaa59-980c-40a9-9043-531735b49989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-documentset-crud']/div/div/div[2]/div/input</value>
      <webElementGuid>3260f4bb-70a8-4019-9c4e-ef4d3f5d1b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>bb58c49f-3579-4579-8814-0e0ecb5e0b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DSName' and @name = 'DSName']</value>
      <webElementGuid>c46be9c1-c66f-4aea-a163-827db9bfb7f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
