<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_DSDescription</name>
   <tag></tag>
   <elementGuidId>492143c2-6322-4c2f-82c5-2e86a20887d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DSDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DSDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67774a43-5b45-4c5e-b409-a6ce1124e3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f941f1ab-1a57-4e99-bbe5-80ee6caec79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d2ed5cb-31ab-4dee-8ff2-b9266c5bcb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DSDescription</value>
      <webElementGuid>217484bf-a804-42cf-bcaa-a989c4e92c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DSDescription</value>
      <webElementGuid>852f3ea3-5391-4d66-8c1f-b32b0ff9e5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DSDescription&quot;)</value>
      <webElementGuid>eb29a687-aa9e-45cf-a3ca-8ef9675140aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DSDescription']</value>
      <webElementGuid>69ffdad5-8a77-4b0d-ad20-ea25c273b632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-documentset-crud']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>3db4047a-e1b4-4b41-9fad-5f5b70002cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>e3e99e63-8ab3-4c39-a773-ba8ab391e1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DSDescription' and @name = 'DSDescription']</value>
      <webElementGuid>2c7c48ed-1959-49d2-8b3f-8a7208aebbef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
